'''
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

'''

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        for e in t:
            if e not in s or t.count(e) > s.count(e):
                return e

        return ""
